### ISSUE TITLE
Debian 8.10 & 7.11 - Can't compile

### ISSUE THREAD

**Issue by harmane** [raphaelsc/Am-I-affected-by-Meltdown#10]
gcc ver Debian 4.7.2-5

> g++ -I. --std=c++11 -O0 --no-pie -mrtm -fPIC -c -o meltdown_checker.o meltdown_checker.cc
g++: error: unrecognized command line option ‘-mrtm’
make: *** [meltdown_checker.o] Error 1

**Comment by raphaelsc** [comment]
@harmane please try again :-)

**Comment by harmane** [comment]
@raphaelsc For what it's worth, still unable to make w/g++ 4.7 in Debian 7.11. build-essential had failed to upgrade on the Debian 8.10 host I had recently migrated from 7.11 hence g++ ver 4.7. With build-essential updated properly everything works.

**Comment by raphaelsc** [comment]
what's the output for gc 4.7? looks like there's another issue now. -mrtm is no longer used for versions lower than 4.8

**Comment by raphaelsc** [comment]
@harmane did you pull latest changes? FWIW

**Comment by raphaelsc** [comment]
@harmane: sorry it was my fix that didn't actually fix anything, now it's fixed after 28016544a82be45b269a856c3c72648cfd528348

**Comment by harmane** [comment]
@raphaelsc Issue is my test host. I ended up upgrading to jessie and still am having issues though system thinks <4.8 of g++ is installed. I've tested on multiple 7.11 hosts in production that work fine after your latest commits. Thanks.
