### ISSUE TITLE
Works fine on Linux Mint Debian Edition

### ISSUE THREAD

**Issue by jvidalgz** [raphaelsc/Am-I-affected-by-Meltdown#5]
Linux version 3.16.0-4-amd64
CPU:  i7-4790

**Comment by raphaelsc** [comment]
@jvidalgz i don't get it, did it work fine to you? or you had any issue running it? thanks. I assume you also bumped into issue #4, right?

**Comment by jvidalgz** [comment]
@raphaelsc Yes, did it work fine. I got 'System affected' message.

**Comment by raphaelsc** [comment]
Glad to know that :-)

**Comment by raphaelsc** [comment]
Closing it given that it's not an actual issue. Thanks for testing it
